---
abstract: 'Provide roles and base classes for processors of'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Temp: 0
  Test::More: 0
  Test::XML::Ordered: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-GrammarBase
provides:
  XML::GrammarBase:
    file: lib/XML/GrammarBase.pm
    version: v0.0.2
  XML::GrammarBase::Role::RelaxNG:
    file: lib/XML/GrammarBase/Role/RelaxNG.pm
    version: v0.0.2
  XML::GrammarBase::Role::XSLT:
    file: lib/XML/GrammarBase/Role/XSLT.pm
    version: v0.0.2
  XML::GrammarBase::Role::XSLT::Global:
    file: lib/XML/GrammarBase/Role/XSLT/Global.pm
    version: v0.0.2
requires:
  File::ShareDir: 0
  Moo::Role: 0
  MooX: 0
  MooX::Role: 0
  MooX::Types::MooseLike: 0
  MooX::late: 0
  Package::Variant: 0
  XML::LibXML: 2.0013
  XML::LibXSLT: 0
  autodie: 0
  strict: 0
  warnings: 0
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v0.0.2
